### ISSUE TITLE
request.DATA is deprecated in favor of request.data

### ISSUE THREAD

**Issue by mike29892** [JamesRitchie/django-rest-framework-expiring-tokens#1]
Line 22 in view.py         serializer = AuthTokenSerializer(data=request.DATA)
should be         serializer = AuthTokenSerializer(data=request.data)

**Comment by JamesRitchie** [comment]
Have opened a branch for this and added a fix, will close the issue when I've sorted versions and released to PyPI.

**Comment by JamesRitchie** [comment]
0.1.2 up on PyPI.
